/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "uhitmgbvbuwmurvxzvca"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoaXRtZ2J2YnV3bXVydnh6dmNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTIwNTUsImV4cCI6MjA3MzQ4ODA1NX0.vL5WBzztAs5Tg5MsZDpIf7kBC0jz-zX-1urZWfwJ8h8"